#!/usr/bin/env python3
"""commit-msg hook — validates commit message against dev-ownership rules.

Checked by git automatically on every commit. No memory required.
Rules enforced: 8 (logical coherence), 12 (review≠retrospect), 13 (no AI signature)
"""

import sys
import re
from pathlib import Path


def check_commit_message(msg_file: str) -> int:
    """Read commit message file, return 0 if valid, 1 if violations found."""
    msg = Path(msg_file).read_text(encoding="utf-8", errors="replace")
    first_line = msg.split("\n")[0].strip()
    violations = 0

    # Rule 12: Review+Retrospect merge detection
    if "review" in first_line.lower() and "retrospect" in first_line.lower():
        print(f"[BLOCKING] Rule 12: Review and Retrospect must be separate commits.")
        print(f"  Found both in: {first_line}")
        print(f"  Split into: docs(review): ... AND docs(retrospect): ...")
        violations += 1

    # Rule 13: AI signature detection
    ai_patterns = [
        r"Co-Authored-By:\s*(Claude|ChatGPT|OpenAI|Copilot|Gemini)",
        r"Generated by",
        r"via Claude Code",
        r"AI-assisted",
        r"🤖",
    ]
    for pattern in ai_patterns:
        if re.search(pattern, msg, re.IGNORECASE):
            print(f"[BLOCKING] Rule 13: AI signatures prohibited in commit messages.")
            print(f"  Found: '{pattern}'")
            print(f"  Record AI assistance in session log, not commit message.")
            violations += 1
            break

    # Rule 8: Logical coherence — "和"/"and" in first line suggests multiple concerns
    and_patterns = [r"\band\b", r"和", r"同时", r"以及"]
    for pattern in and_patterns:
        if re.search(pattern, first_line, re.IGNORECASE):
            print(f"[WARN] Rule 8: Commit message may contain multiple concerns.")
            print(f"  First line: {first_line}")
            print(f"  If this commit does multiple things, split into separate commits.")
            # WARN only — don't block
            break

    if violations > 0:
        print(f"\n{violations} violation(s) found. Commit blocked.")
        print("Fix the commit message and retry.")
        return 1

    return 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: commit-msg <message-file>")
        sys.exit(1)

    msg_file = sys.argv[1]
    sys.exit(check_commit_message(msg_file))
